version: "3"
services:
  db:
    image: mysql:8.0.29
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "./webapp/sql/admin:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=root
